# Generated by Django 5.2.7 on 2025-10-31 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU/Código Interno')),
                ('codigo_barras', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Código de Barras (EAN)')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('ncm', models.CharField(max_length=8, verbose_name='NCM (Nomenclatura Comum do Mercosul)')),
                ('cest', models.CharField(blank=True, max_length=7, null=True, verbose_name='CEST')),
                ('origem_mercadoria', models.PositiveSmallIntegerField(choices=[(0, 'Nacional'), (1, 'Estrangeira - Importação Direta'), (2, 'Estrangeira - Adquirida no Mercado Interno')], default=0, verbose_name='Origem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo para Venda')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
