# Generated by Django 5.2.7 on 2025-10-31 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras_variacao', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Cód. de Barras Específico')),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Adicional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Variação do Produto',
                'verbose_name_plural': 'Variações dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Variação')),
            ],
            options={
                'verbose_name': 'Variação (Tipo)',
                'verbose_name_plural': 'Variações (Tipos)',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('produto_variacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalogo.produtovariacao', verbose_name='Item de Estoque')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade Atual')),
                ('quantidade_minima', models.IntegerField(default=5, verbose_name='Estoque Mínimo de Alerta')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
            },
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='variacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.variacao'),
        ),
        migrations.AlterUniqueTogether(
            name='produtovariacao',
            unique_together={('produto', 'variacao')},
        ),
    ]
