# Generated by Django 5.2.7 on 2025-10-31 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_produtovariacao_variacao_estoque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venda', models.IntegerField(unique=True, verbose_name='Número da Venda')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Venda')),
                ('status', models.CharField(choices=[('A', 'Aberta'), ('F', 'Fechada'), ('C', 'Cancelada'), ('P', 'Pendente (Contingência)')], default='F', max_length=1, verbose_name='Status')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total')),
                ('desconto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto Aplicado')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário na Venda')),
                ('desconto_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto no Item')),
                ('produto_variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.produtovariacao', verbose_name='Produto Vendido')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='catalogo.venda', verbose_name='Venda Associada')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
            },
        ),
    ]
