# Generated by Django 5.2.7 on 2025-10-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_cliente_venda_itemvenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Categoria'),
        ),
    ]
