# Generated by Django 5.2.7 on 2025-11-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_categoria_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='numero_venda',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
