# Generated by Django 5.2.7 on 2025-11-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_venda_numero_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='numero_venda',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
